[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
#decorations = "None"

[font]
size = 13

[keyboard]
bindings=[
    { key = "c", mods = "Control", action = "Copy" },
    { key = "v", mods = "Control", action = "Paste" },
    { key = "c", mods = "Control|Shift", chars = "\u0003" }, # SIGINT
    { key = "=", mods = "Control", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
    { key = "n", mods = "Control", action = "CreateNewWindow" },
    { key = "p", mods = "Control|Shift", action = "SearchForward" },
    { key = "o", mods = "Control|Shift", action = "SearchBackward" },
    { key = "F11", action = "ToggleFullscreen" },

    # They claim these are macOS only?
    { key = "{", mods = "Control", action = "SelectPreviousTab" },
    { key = "}", mods = "Control", action = "SelectNextTab" },
]

[general]
live_config_reload = true
import = [ "~/.config/alacritty/kanagawa.toml" ]
